<?php

namespace App\Presenters;

use Nette;
use Nette\Application\UI\Form;
use Nette\ComponentModel\IContainer;
use Nette\Security\User;

class HomepagePresenter extends \BasePresenter {

  public $ArticleModel;
  public $UserModel;

  public function startup() {
    parent::startup(); // TODO: Change the autogenerated stub
    if ($this->user->isLoggedIn() && ($this->isLinkCurrent('Homepage:login') || $this->isLinkCurrent('Homepage:registration'))) {
      $this->flashMessage('Už jste přihlášen');
      $this->redirect('Administration:administration');
    }
    $this->ArticleModel = $this->context->createService('ArticleModel');
    $this->UserModel = $this->context->createService('UserModel');
  }

  public function renderArticle() {
    $url = $this->getParameter('url');
    $this->template->articles = $this->ArticleModel->getArticles();
    $this->template->userModel = $this->UserModel;
    $this->template->url = $url;
    bdump($url);
    if($url) {
      $this->template->article = $this->ArticleModel->getArticlebyUrl($url);
    }
  }

  public function createComponentRegistracionForm() {
    $form = new Form();
    $form->setHtmlAttribute('class', 'validation');
    $form->addText('first_name')
         ->setRequired('Jméno: ' . \Constants::FORM_MSG_REQUIRED)
         ->addRule(FORM::MIN_LENGTH, \Constants::FORM_SHORT_FIRSTNAME, 3)
         ->addRule(FORM::MAX_LENGTH, \Constants::FORM_LONG_FIRSTNAME, 250)
         ->setHtmlAttribute('placeholder', 'Jméno*');
    $form->addText('last_name')
         ->setRequired('Přijmení: ' . \Constants::FORM_MSG_REQUIRED)
         ->addRule(FORM::MIN_LENGTH, \Constants::FORM_SHORT_LASTNAME, 3)
         ->addRule(FORM::MAX_LENGTH, \Constants::FORM_LONG_LASTNAME, 250)
         ->setHtmlAttribute('placeholder', 'Přijmení*');
    $form->addEmail('email')
         ->setRequired('email: ' . \Constants::FORM_MSG_REQUIRED)
         ->addRule(FORM::EMAIL, \Constants::FORM_VALID_EMAIL)
         ->setHtmlAttribute('placeholder', 'email*');
    $form->addPassword('passwd')
         ->setRequired('Heslo: ' . \Constants::FORM_MSG_REQUIRED)
         ->addRule(FORM::MIN_LENGTH, \Constants::FORM_SHORT_PASSWD, 5)
         ->addRule(FORM::MAX_LENGTH, \Constants::FORM_LONG_PASSWD, 30)
         ->setHtmlAttribute('placeholder', 'Heslo*');
    $form->addPassword('passwd_verify')
         ->setRequired('Heslo: ' . \Constants::FORM_MSG_REQUIRED)
         ->setHtmlAttribute('placeholder', 'Heslo ověření*')
         ->setOmitted()
         ->addRule(Form::EQUAL, 'Zadaná hesla se neschodují.', $form['passwd']);
    $form->addSubmit('registration', 'Registrovat');
    $form->onSuccess[] = [$this, 'RegistracionFormSucceeded'];
    return $form;
  }

  public function RegistracionFormSucceeded($form, $values) {
    $userModel = $this->context->createInstance('UserModel');
    try {
      $userModel->newUser($values);
    } catch (\Exception $e) {
      $this->flashMessage($e->getMessage(), 'error');
      $this->redirect('this');
    }
    $this->flashMessage('Byl jste úspěšně zaregistrován.');
    $this->redirect('Homepage:login');
  }

  public function createComponentLoginForm() {
    $form = new Form();
    $form->addEmail('email')
         ->setRequired('email: ' . \Constants::FORM_MSG_REQUIRED)
         ->addRule(FORM::EMAIL, \Constants::FORM_VALID_EMAIL)
         ->setHtmlAttribute('placeholder', 'email');
    $form->addPassword('passwd')
         ->setRequired('heslo: ' . \Constants::FORM_MSG_REQUIRED)
         ->addRule(FORM::MIN_LENGTH, \Constants::FORM_SHORT_PASSWD, 5)
         ->addRule(FORM::MAX_LENGTH, \Constants::FORM_LONG_PASSWD, 30)
         ->setHtmlAttribute('placeholder', 'Heslo');
    $form->addSubmit('login', 'Přihlásít');
    $form->onSuccess[] = [$this, 'LoginFormSucceeded'];
    return $form;
  }

  public function LoginFormSucceeded($form, $values) {
    try {
      $this->getUser()
           ->login($values->email, $values->passwd);
      $this->flashMessage('Byl jste úspěšně přihlášen.');
      $this->redirect('Administration:administration');
    } catch (\Nette\Security\AuthenticationException $e) {
      $this->flashMessage($e->getMessage());
    }
  }

  public function actionOut() {
    $this->getUser()
         ->logout();
    $this->flashMessage('Byl jste odhlášen.');
    $this->redirect('Homepage:default');
  }
}
